<?php

namespace vente_detailsBundle\Repository;

/**
 * ventdetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ventdetRepository extends \Doctrine\ORM\EntityRepository
{
}
