facture_fac:
    resource: "@factureBundle/Controller/facController.php"
    type:     annotation

vente.details_ventdet:
    resource: "@vente_detailsBundle/Controller/ventdetController.php"
    type:     annotation

achat.details_achadet:
    resource: "@achat_detailsBundle/Controller/achadetController.php"
    type:     annotation

ventes_vent:
    resource: "@ventesBundle/Controller/ventController.php"
    type:     annotation

achats_ach:
    resource: "@achatsBundle/Controller/achController.php"
    type:     annotation

client_cli:
    resource: "@clientBundle/Controller/cliController.php"
    type:     annotation

fournisseur_four:
    resource: "@fournisseurBundle/Controller/FourController.php"
    type:     annotation

acceuil:
    resource: "@acceuilBundle/Resources/config/routing.yml"
    prefix:   /

article_art:
    resource: "@articleBundle/Controller/artController.php"
    type:     annotation

user:
    resource: "@userBundle/Resources/config/routing.yml"
    prefix:   /


facture:
    resource: "@factureBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@articleBundle/Resources/config/routing.yml"
    prefix:   /

vente.details:
    resource: "@vente_detailsBundle/Resources/config/routing.yml"
    prefix:   /

ventes:
    resource: "@ventesBundle/Resources/config/routing.yml"
    prefix:   /

achat.details:
    resource: "@achat_detailsBundle/Resources/config/routing.yml"
    prefix:   /

achats:
    resource: "@achatsBundle/Resources/config/routing.yml"
    prefix:   /

client:
    resource: "@clientBundle/Resources/config/routing.yml"
    prefix:   /

fournisseur:
    resource: "@fournisseurBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app2: 
    resource: '@AppBundle/Resources/config/routing.yml' 
    prefix: /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml" 
     
fos_user_profile:   
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    
fos_user_resister :   
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
fos_user_resetting:  
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile        
 