security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                # Use form.csrf_provider instead for Symfony <2.4
                csrf_token_generator: security.csrf.token_manager 
                #success_handler: redirect.after.login
             
                login_path: /login
                use_forward: false

                # login success redirecting options (read further below)
             #   always_use_default_target_path: false
             #   default_target_path:     /user/pub/         

            logout:       
                path:   /logout
            #lorsque on fait un logout on se rédérige vers la page /login
                target: /
            anonymous:    true

    access_control:
        - { path: ^/login$, role:  IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role:  IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
