<?php

namespace clientBundle\Repository;

/**
 * cliRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cliRepository extends \Doctrine\ORM\EntityRepository
{
}
