<?php

namespace ventesBundle\Repository;

/**
 * ventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ventRepository extends \Doctrine\ORM\EntityRepository
{
}
