<?php

namespace fournisseurBundle\Repository;

/**
 * FourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FourRepository extends \Doctrine\ORM\EntityRepository
{
}
