<?php

namespace achat_detailsBundle\Repository;

/**
 * achadetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class achadetRepository extends \Doctrine\ORM\EntityRepository
{
}
