<?php

namespace articleBundle\Repository;

/**
 * artRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class artRepository extends \Doctrine\ORM\EntityRepository
{
}
