<?php

namespace achatsBundle\Repository;

/**
 * achRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class achRepository extends \Doctrine\ORM\EntityRepository
{
}
